# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch and develop branch
on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: 'x64'
    - name: Install pipenv and dependencies
      run: |
        pip install pipenv --upgrade-strategy=only-if-needed
        pipenv sync --dev
    - name: Run test
      run: |
        pipenv run pytest 
